### ISSUE TITLE
Could not find io.insert-koin:koin-annotations:1.0.0-beta-1.

### ISSUE THREAD

**Issue by stankinzl** [InsertKoinIO/koin-annotations#1]
Hi, this looks promising, I'd love to define singletons and factories just by annotating the class, thus avoiding having to declare it in my module every time.

But when I try to run the sample app or add it to my project based on the guide provided I get the following error:

> Could not resolve all files for configuration ':getting-started-koin-android:app:debugRuntimeClasspath'.
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find io.insert-koin:koin-annotations:1.0.0-beta-1.

Do you know why this might be?
Thanks

**Comment by mr-w1lde** [comment]
Same thing

**Comment by mr-w1lde** [comment]
@stankinzl okay, it is work now for me. Try it again

**Comment by arnaudgiuliani** [comment]
still getting problem?
