### ISSUE TITLE
I can't use 1.0.0-beta-2 there is a warning gradle unable to resolve.

### ISSUE THREAD

**Issue by Egi10** [InsertKoinIO/koin-annotations#10]
I can't use 1.0.0-beta-2 there is a warning gradle unable to resolve. Because of this warning I can't use annotations on Koin Annotations.

But if I downgrade Koin Annotations to 1.0.0-beta-1 there is no warning problem in gradle, and I can use the annotations.

Thanks you

**Comment by egorikftp** [comment]
Looks like artifact wasn't available on maven few days ago. Now works as expected.
Please try again

**Comment by Egi10** [comment]
thank you, now I can use it again
