### ISSUE TITLE
@Module(createdAtStart=true)

### ISSUE THREAD

**Issue by clembo590** [InsertKoinIO/koin-annotations#100]
when using koin-core we can  create a module and force the creation of `singletons` at the start like this:

```
val koinModule = module(createdAtStart = true) {
....
```

when using annotations like this:
```
@Module
@ComponentScan("my.wonderfull.app")
class KoinConfiguration {
```
the generated is like this and there is no way to create the module with `createdAtStart = true`
```
public val my_wonderfull_app_KoinConfiguration : Module = module {
```

Of course I can set up `createdAtStart` for every singleton but if you have 100 singletons annotations (100 x `@Single`) then it becomes pretty repetitive.

My suggestion is to add a parameter to the @Module annotation
From this
```
annotation class Module(val includes: Array<KClass<*>> = [])
```
to 
```
annotation class Module(val includes: Array<KClass<*>> = [], val createdAtStart: Boolean = false)
```

and then of course use this value to generate the appropriate code.
Is that possible ?

**Comment by ghasemdev** [comment]
I create an PR https://github.com/InsertKoinIO/koin-annotations/pull/106

**Comment by arnaudgiuliani** [comment]
Yes, that's a missing parameter for modules 👍

**Comment by arnaudgiuliani** [comment]
le's follow on https://github.com/InsertKoinIO/koin-annotations/pull/106
