### ISSUE TITLE
[Help wanted] Migrating from Dagger to Koin Annotations: StackOverflowError

### ISSUE THREAD

**Issue by JSmyth886** [InsertKoinIO/koin-annotations#104]
I'm migrating from an old version of Dagger to the latest version of Koin (3.5.0) and Koin Annotations (1.3.0), and I've ran into an StackOverflowError when attempting to run. I think what is happening is a recursive call of some sort, due to the structure of the dependencies within the project though I'm not 100% sure and I'm struggling to pinpoint the offending dependency.

I know this isn't an issue with Koin itself, I'm more wondering if there was any tips on tracking down the offending code or if I'd be better using the DSL for migrating from Dagger as I would have better control over the dependencies and how they're marked.

Apologies, I can't provide much more information as it's a company project. 

Please find attached [logcat.txt](https://github.com/InsertKoinIO/koin-annotations/files/13560610/logcat.txt), which has the entire trace from the beginning of the crash to the last line with our package name involved.

**Comment by arnaudgiuliani** [comment]
The best is to go step by step in your system, and migrate Koin by bridging with `KoinComponent` interface: 
Having a component yet declared in Dagger, but pulling dependencies from Koin. Try to spot simple isolated and/or parts.

This way you can unlock progressively your app.

**Comment by JSmyth886** [comment]
Ah I hadn't thought about using both Dagger and Koin at the same time, thanks for the response and apologies for the late reply/close.
