### ISSUE TITLE
Dependency resolve problem from another module

### ISSUE THREAD

**Issue by kerimovscreations** [InsertKoinIO/koin-annotations#12]
I'm using the annotations to implement a clean architecture multi-module Android application. In this setting, I have two modules - `DomainModule` and `DataModule`. `data` module includes `domain` module (`domain` module cannot access directly `data` module). I have an interface in `domain` module and its implementation is declared in `data` module. Now I face the issue, the implementation cannot resolve in the `domain` module. I have experience with the previous version of Koin too, there was not such a problem. I guess, resolved modules are not binded at the top level (in my case, global application class)

* domainModule
	* RepoInterface

* dataModule
	* RepoImplementation

**To Reproduce**
1. Create 2 gradle modules: `data` and `domain`
2. Inluce `domain` into `data`
3. Create an interface in `domain`
4. Create an implementation of the previous interface in `data`
5. Try to access this implementation in `domain` module

**Expected behavior**
Implementation of interface from another module should be resolved, as we are binding them at the top level: `modules(listOf(DataModule().module, DomainModule().module))`

**Koin project used and used version:**
```
koinVersion = "3.2.0-beta-1"
koinKspVersion = "1.6.20-1.0.5"
koinAnnotationsVersion = "1.0.0-beta-1"


implementation "io.insert-koin:koin-core:$koinVersion"
implementation "io.insert-koin:koin-annotations:$koinAnnotationsVersion"
ksp "io.insert-koin:koin-ksp-compiler:$koinAnnotationsVersion"
```

**Comment by aerain** [comment]
I think it's duplicates of #7

**Comment by kerimovscreations** [comment]
@aerain thanks for the reference!. The beta-2 version was not available in mavenCentral, when I was testing. It's working now.
