### ISSUE TITLE
Add Wasm support

### ISSUE THREAD

**Issue by codeofmario** [InsertKoinIO/koin-annotations#120]
**Is your feature request related to a problem? Please describe.**
Wasm target is not supported by koin-annotations.

**Describe the solution you'd like**
Add Wasm target.

**Describe alternatives you've considered**

**Target Koin project**
koin-annotations

**Comment by Deorigami** [comment]
is there any date target for this ?

**Comment by arnaudgiuliani** [comment]
Should be shipped for 1.4.0

**Comment by arnaudgiuliani** [comment]
added in #134
