### ISSUE TITLE
ViewModel KMP support

### ISSUE THREAD

**Issue by frankois944** [InsertKoinIO/koin-annotations#130]
Hello,

As the https://github.com/InsertKoinIO/koin/issues/1826 is now implemented.

I'm using koin annotation in a KMP project with viewmodel.

I'm using the annotation `@KoinViewModel` in the Shared project.

The issue is on iOS target :

The generate code is 

```Kotlin
import org.koin.androidx.viewmodel.dsl.viewModel 
internal val mypackage_SharedModule : Module = module {
	viewModel() { mypackage.MainScreenViewModel() } bind(org.koin.core.component.KoinComponent::class)
}
```

the viewmodel is missing as org.koin.androidx.**viewmodel**.dsl.viewModel is not founded.

For the iOS target, i'm using the dependancies : "koin-core" and "koin-compose".

I'm missing something ?

Thanks

**Comment by frankois944** [comment]
There is a workaround for now, 
it's manually declaring the viewmodel on the Android app source instead using annotation.

Like: 
```kotlin
@Module
internal class AndroidModule {
    @KoinViewModel
    fun mainScreenViewModel(parameters: String? = null): MainScreenViewModel {
        return MainScreenViewModel(param1 = parameters)
    }
}
```

**Comment by frankois944** [comment]
@arnaudgiuliani some news about Koin annotation and KMP ViewModel?

**Comment by arnaudgiuliani** [comment]
KMP ViewModel for Compose has landed in Koin 3.6. We should be able to generate ViewModel for compose at least.

**Comment by frankois944** [comment]
> KMP ViewModel for Compose has landed in Koin 3.6. We should be able to generate ViewModel for compose at least.

On the commonMain, the generated code is working if I'm targetting Android (and has the correct dependancy in the commonAndroid) but not for iOS, it doesn't have the deps.

**Comment by arnaudgiuliani** [comment]
>but not for iOS, it doesn't have the deps.

Compose MP ViewModel is available on common sources

**Comment by frankois944** [comment]
A PR about the issue : https://github.com/InsertKoinIO/koin-annotations/pull/133

**Comment by arnaudgiuliani** [comment]
let's follow up on PR

**Comment by heesung6701** [comment]
@frankois944 with our case, we fixed this issue with below method temporary.

made below file on commonMain for making generated file reference it.

```
package org.koin.androidx.viewmodel.dsl

import androidx.lifecycle.ViewModel
import org.koin.core.definition.Definition
import org.koin.core.definition.KoinDefinition
import org.koin.core.module.Module
import org.koin.core.qualifier.Qualifier

public inline fun <reified T : ViewModel> Module.viewModel(
    qualifier: Qualifier? = null,
    noinline definition: Definition<T>
): KoinDefinition<T> {
    return factory(qualifier, definition)
}
```
