### ISSUE TITLE
KOIN_USE_COMPOSE_VIEWMODEL does not work

### ISSUE THREAD

**Issue by master-lzh** [InsertKoinIO/koin-annotations#150]
**Describe the bug**
No matter where I add 
```kts
ksp { 
    arg("KOIN_USE_COMPOSE_VIEWMODEL", "true")
}
```
, it still import `org.koin.androidx.viewmodel.dsl.viewModel`

**Expected behavior**
import `org.koin.compose.viewmodel.dsl.viewModel`

**Koin project used and used version (please complete the following information):**
koin-ksp-compiler 1.4.0-RC3

**Additional moduleDefinition**
Add any other moduleDefinition about the problem here.

**Comment by kibettheophilus** [comment]
Hi @master-lzh , can you try removing the ksp argument? Seems it is deprecated as of version `1.4.*`.

**Comment by frogggias** [comment]
@kibettheophilus The issue is in configuring the code writer for the default module. See fixed #157 .

**Comment by kibettheophilus** [comment]
@frogggias you are right, hadn't checked the imports well on the generated file.
