### ISSUE TITLE
Failed when generate AppModule without package.

### ISSUE THREAD

**Issue by adamglin0** [InsertKoinIO/koin-annotations#153]
**Describe the bug**
when put AppModule in root(without any package), generated code is in the syntax error.

```kotlin
@Module
@ComponentScan
class AppModule
```

put in root
<img width="237" alt="image" src="https://github.com/user-attachments/assets/d149ed26-e418-42be-b90b-817e8bd2754d">

generated code

```kotlin
package org.koin.ksp.generated

import org.koin.core.module.Module
import org.koin.dsl.*


public val _AppModule : Module get() = module {
	single() { MyComponent() } 
}
public val .AppModule.module : org.koin.core.module.Module get() = _AppModule
```

**To Reproduce**
Here is the git repository.
https://github.com/adamglin0/koin-annotations-bug-sample

**Comment by arnaudgiuliani** [comment]
Should be already fixed in 1.4.0 (wait for release)
