### ISSUE TITLE
Impossible to include koin module from another gradle module

### ISSUE THREAD

**Issue by DoTheMonkeyBusiness** [InsertKoinIO/koin-annotations#18]
**Describe the bug**
ksp doesn generate path to koin module from another gradle module when I try to include it into main koin module.

**To Reproduce**

1.  Create gradle module and plug it into main gradle module.
2. Try to include koin module from submodule into main koin module:
```
@Module(includes = [SubmoduleModule::class])
@ComponentScan("com.example.koinissue.common")
class CommonModule
```

3. Build project

**Expected behavior**
Ksp generates path to `SubmoduleModule`.

**Actual behavior**
Ksp doesn't generate path to `SubmoduleModule` and throws an exception.

Generated file:
```
val CommonModuleModule = module {
	includes(.SubmoduleModule().module)
	single(qualifier=null) { com.example.koinissue.common.SampleClass() } 
}
val com.example.koinissue.common.koin.CommonModule.module : org.koin.core.module.Module get() = CommonModuleModule
```

`koin-core version 3.2.0-beta-1`
`koin-annotations version 1.0.0-beta-2`

**Additional**
Sample code: https://github.com/DoTheMonkeyBusiness/koinAnnotationIssue/tree/Submodule_issue

**Comment by 4face-studi0** [comment]
The issue seems to be there also in the latest release.
Is there any plan to address this, or is there any alternative solution?

**Comment by arnaudgiuliani** [comment]
The module package generation has been fixed.
