### ISSUE TITLE
The Library incorrectly generates files for a multi-platform project

### ISSUE THREAD

**Issue by DoTheMonkeyBusiness** [InsertKoinIO/koin-annotations#19]
**Describe the bug**
Highlighting in Android Studio doesn't work when using generated resources in a multi-platform project

**To Reproduce**
1. Add koin-annotations to a multiplatform project.
2. Add all necessary modules.
3. Try to register modules.

**Expected behavior**
Highlighting in Android Studio works as expected.

**Actual behavior**
Highlighting in Android Studio doesn't work as expected.

This happens because when I add generated platform folders to `srcDir`, Android Studio still expects the `common` path:
I add `kotlin.srcDir("build/generated/ksp/android/androidDebug/kotlin")` for android
and `kotlin.srcDir("build/generated/ksp/desktop/desktopMain/kotlin")` for desktop

And Adnroid studio sees them:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/36794185/163830584-09d52781-b7dd-47f1-8805-0f0ef4b545fd.png">

But still doesn't see generated code from common code:
<img width="433" alt="image" src="https://user-images.githubusercontent.com/36794185/163830690-a704d2b4-aabc-4c5a-a9d9-332ab11f445d.png">

**Important**
I can build the project, this issue affects only visual representation.

`koin-core version 3.2.0-beta-1`
`koin-annotations version 1.0.0-beta-2`

**Additional**
Sample code: https://github.com/DoTheMonkeyBusiness/koinAnnotationIssue/tree/multiplatform_exception

**Comment by arnaudgiuliani** [comment]
The issue is duplicated
