### ISSUE TITLE
Builds not reproducible due to metadata files containing hash codes

### ISSUE THREAD

**Issue by AkesiSeli** [InsertKoinIO/koin-annotations#200]
**Is your feature request related to a problem? Please describe.**
Some stores (e.g. F-Droid) require build to be reproducible and perform some checks on the contents of APKs. After migrating a project from using the Koin DSL to annotations, builds started to not be reproducible any more, apparently due to some files (e.g. `KoinMeta-*.kt`) having an hash in their name which changes at every build.

See, [this bug report](https://github.com/LiveFastEatTrashRaccoon/RaccoonForFriendica/issues/657) for more information.

**Describe the solution you'd like**
I've tried excluding the `**/KoinMeta-*.kt `path from the KotlinCompile task but it seems to make the build fail due to duplicate definitions.

I hope there is some way around this, or wait for the next version of koin-annotations (I'm currently on `2.0.0-Beta2`).

**Describe alternatives you've considered**
Migrating everything back to the DSL, which is something I would rather not do. Firstly because I've completed the reverse migration a couple of weeks ago and would rather not revert everything, secondly because I think annotations is the way to go and makes the code more flexible (I still have nightmares about having to change my module definitions manually each time I added a constructor parameter).

**Comment by AkesiSeli** [comment]
Nevermind, I switched to a different DI framework, so this can be closed. I suggest this should be mentioned in the documentation because developers need be informed of this limitation before choosing.

**Comment by arnaudgiuliani** [comment]
Ok too bad. Missed this one. Sorry
