### ISSUE TITLE
Upgrade koin from 2.0.1 to 3.2.0

### ISSUE THREAD

**Issue by Anirban2022** [InsertKoinIO/koin-annotations#25]
**Describe the bug**
Error after upgrading koin 
> No definition found for class:MyUseCase & qualifier: MyUseCase

**Koin project used and used version (please complete the following information):**
After the upgrade we are using:
`io.insert-koin:koin-android:3.2.0`
`io.insert-koin:koin-core:3.2.0`
`io.insert-koin:koin-test:3.2.0`

Previously it was:
`org.koin:koin-android-viewmodel:2.0.1`
`org.insert-koin:koin-android:2.0.1`
`org.insert-koin:koin-core:2.0.1`
`org.insert-koin:koin-test:2.0.1`

**To Reproduce**
In our previous implementation we used it it this way:
`  single<BaseUseCase<Int, String>>(named(MY_USE_CASE)) {
    MyUseCase(get(), get())
  }`

After the update we changed to this way:
`single{MyUseCase(get(), get()) } bind BaseUseCase::class`

**Comment by arnaudgiuliani** [comment]
there is a missing qualifier on your definition. Try add `@Named(MY_USE_CASE)` in your case.
