### ISSUE TITLE
@ComponentScan does not work in multimodules project.

### ISSUE THREAD

**Issue by ArturWal** [InsertKoinIO/koin-annotations#27]
Describe the bug
@ComponentScan configured for given package only scans package in current gradle module. Other gradle modules with same package name are not scanned.

To Reproduce

Setup a KMP project
Create some module and mark it as @ComponentScan(value ="packageName")
Create some class X  in other gradle module in package "packageName" and mark as @Single
Try to inject the class X somewhere
Build
See error
Expected behavior
It should be possible to inject the class.

Koin project used and used version (please complete the following information):
koin-core version 3.2.0-beta-1
koin-ksp 1.0.0-beta-1
ksp version 1.6.10-1.0.2

**Comment by arnaudgiuliani** [comment]
it's a currently known limitation. KSP analyses is done on the current Gradle module. We can't reach other definitions ... unless we find a way to see that 🤔
