### ISSUE TITLE
ComponentScan as a list of packages

### ISSUE THREAD

**Issue by mr-w1lde** [InsertKoinIO/koin-annotations#3]
**Is your feature request related to a problem? Please describe.**
I have a multi-model project and the interfaces in project A don't bind in project B

**Describe the solution you'd like**
Provide an opportunity to specify the packages in ComponentScan annotation

**Comment by arnaudgiuliani** [comment]
You would need to specify several packages in @ComponentScan?

**Comment by mr-w1lde** [comment]
@arnaudgiuliani yes, I think something like that

**Comment by mr-w1lde** [comment]
@arnaudgiuliani my issue is related by this problem https://github.com/InsertKoinIO/koin-annotations/issues/7

**Comment by arnaudgiuliani** [comment]
Then is it just a problem to use external package/interface, or your need is to have a Module to cover many packages?

**Comment by mr-w1lde** [comment]
@arnaudgiuliani, Hi! Sorry for the long answer.

I have the following project structure: two app projects (com.example.app, com.example.secondApp) and one core lib (com.example.core) with described interfaces. And when I applied @Single annotation on class in **com.example.app** package, and class implements an interface from **com.example.core** package, ksp ignoring a binding of a class. 
![Uploading Screenshot 2022-04-30 at 18.14.35.png…](should be)
![Uploading Screenshot 2022-04-30 at 18.14.44.png…](generating without binding => koin doesn't inject by interface)

**Comment by mr-w1lde** [comment]
and to "fix that" I just rewrite my interfaces in com.example.app class and additionally specified binding
<img width="701" alt="Screenshot 2022-04-30 at 18 21 08" src="https://user-images.githubusercontent.com/44321056/166109421-9c0da0fd-5be4-452a-8fc3-3d5c119946a9.png">
<img width="701" alt="Screenshot 2022-04-30 at 18 20 07" src="https://user-images.githubusercontent.com/44321056/166109423-5900de63-2c9d-4ecb-98b2-cc12ed0779e1.png">

**Comment by mr-w1lde** [comment]
oh... I upgraded to the second beta and it solved my problem :D

**Comment by vdshb** [comment]
The issue is closed, workarounds are available (I'm using @Module::includes), but is there a way to scan multiple packages using one class with @ComponentScan annotation(s)?
