### ISSUE TITLE
Build error when package name starts with id.***

### ISSUE THREAD

**Issue by Egi10** [InsertKoinIO/koin-annotations#30]
**Describe the bug**
I created a project with the package name **id.buaja.example**. When I rebuild this project, an error occurs with the **unresolved** **reference buaja**.

This is because **id** is already used on :
org.koin.core.scope.Scope public final val id: ScopeID /* = String */
  Gradle: io.insert-coins:coins-core-jvm:3.2.0-beta-1

that's why he got an error.

When I change the package name to **com.buaja.example** everything will work normally as it should.

**To Reproduce**
1. Create project package name **id.buaja.example**
2. Create inject with koin
3. Rebuild project
4. Error unresolved reference buaja

**Expected behavior**
What I hope is that when I make the package name id.buaja.example everything will be fine

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 3.2.0-beta-1` , `koin-annotation version 1.0.0-beta-2`

**Comment by Egi10** [comment]
@arnaudgiuliani I have updated to version:

Koin : 3.2.0
Koin annotation : 1.0.0

the result is still the same, still can't use the package with the name id.***


<img width="700" alt="Screen Shot 2022-06-13 at 19 57 35" src="https://user-images.githubusercontent.com/21285006/173359171-45b071ce-a1de-4ffa-ac3f-8ad7b42df952.png">
<img width="1033" alt="Screen Shot 2022-06-13 at 19 56 08" src="https://user-images.githubusercontent.com/21285006/173359212-ad9c5f75-ab57-42bf-8f4d-8fa8909100ea.png">

**Comment by arnaudgiuliani** [comment]
still there in latest version? Try 1.1.0 soon 👍
