### ISSUE TITLE
Generated code does not use getAll() for List type constructor parameters

### ISSUE THREAD

**Issue by PaulWMR** [InsertKoinIO/koin-annotations#37]
**Describe the bug**
When a class's constructor takes a parameter of type List, the generated module specifies get() instead of getAll() when I am providing separate components for each type. When running the application, I get an error: I have not provided a component of type 'List'

**To Reproduce**
Run the following app:
```
interface MyInterface {
    fun doRun()
}

@Single
class MyInterfaceImpl1: MyInterface {
    override fun doRun() {
        println("Running first impl")
    }
}

@Single
class MyInterfaceImpl2: MyInterface {
    override fun doRun() {
        println("Running second impl")
    }
}

@Single
class MyInterfaceCollection(val myInterfaces: List<MyInterface>) {
    fun runAll() {
        myInterfaces.forEach(MyInterface::doRun)
    }
}

class MyComponent : KoinComponent {
    
    val collection: MyInterfaceCollection by inject

    fun run() {
        collection.runAll()
    }
}

fun main() {
    startKoin {
        defaultModule()
    }

    MyComponent().run()
}
```

The application throws an ExceptionInInitializerError caused by a NoBeanDefFoundException: No definition found for class: 'java.util.List'

**Expected behavior**
I expect all instances of implementation of MyInterface to be injected into MyInterfaceCollection.
Alternatively, if this cannot be supported out of the box or if this is deemed unwanted default behaviour, would it be possible to create an additional annotation to use on the parameter, to make it generate a getAll() call instead of a get() call?

**Koin project used and used version (please complete the following information):**
 koin-core version 3.2.0
 koin-annotations version 1.0.1

**Comment by PaulWMR** [comment]
I have created https://github.com/InsertKoinIO/koin-annotations/pull/38 to give the option for getAll() instead of get() when working with lists.

**Comment by arnaudgiuliani** [comment]
Yep, let's continue on your PR
