### ISSUE TITLE
Wrong import path for a nested class

### ISSUE THREAD

**Issue by hennihaus** [InsertKoinIO/koin-annotations#40]
**Describe the bug**
Hello together, I really like the new koin annotation framework. Thanks for creating this library. Unfortunately, I am not able to generate the correct import path for a nested abstract class. Koin does not add the outer class to the import path. I guess the example below is a better way to understand the problem.

**To Reproduce**
1. 
![Bildschirmfoto 2022-07-02 um 19 49 53](https://user-images.githubusercontent.com/47771386/177011390-800da7aa-bc52-40d1-aaf1-bb84d6d5ca6e.png)
2. 
![Bildschirmfoto 2022-07-02 um 19 50 19](https://user-images.githubusercontent.com/47771386/177011401-4be92af2-5efb-43fe-a51b-3382c8e54eec.png)

**Expected behavior**
![Bildschirmfoto 2022-07-02 um 20 01 12](https://user-images.githubusercontent.com/47771386/177011550-e0173f31-8fab-41c4-a97b-a66260659a28.png)

**Koin project used and used version (please complete the following information):**
compileOnly("io.insert-koin:koin-annotations:1.0.1")

**Comment by arnaudgiuliani** [comment]
did you try to add `open` to `AbstractClass`? It can be still internal for your class 🤔
