### ISSUE TITLE
KSP code generation bug

### ISSUE THREAD

**Issue by andriishpek-sigma** [InsertKoinIO/koin-annotations#44]
**Description**
Generated Koin module doesn't respect nested interfaces (parents of nested interfaces)

**To Reproduce**
1. Declare nested interface (see code below - `SymptomRarity.Transformer`)
2. Create nested interface implementation (see code below - `SymptomRarityToScoreTransformer`)
3. Mark interface implementation with `@Factory` annotation
4. Create module class marked with `@Module` and `@ComponentScan("...")` annotations
5. Build project
6. See _unresolved reference_ error in generated file - interface implementation binding doesn't include parent interface into the full class path (see below)

**Koin project used and used version (please complete the following information):**
`koin-core version 3.2.0`
`koin-annotations version 1.0.1`

**Notes**
Nested interface binding path is also incorrect if interface parent is abstract class 

**Nested interface declaration**

```
interface SymptomRarity {

    fun <T> transform(transformer: Transformer<T>): T

    interface Transformer<T> {
        ...
    }
}
```

**Nested interface implementation**

```
@Factory
class SymptomRarityToScoreTransformer : SymptomRarity.Transformer<Int> {
    ...
}
```

**Generated module code - invalid class path**
```
factory(qualifier=null) { <...>.transformers.SymptomRarityToScoreTransformer() } bind(<...>.models.Transformer::class)
```

**Expected result**

Line of code above should bind class with path `<...>.models.SymptomRarity.Transformer::class`

**Comment by andriishpek-sigma** [comment]
I've just noticed a similar issue. Seems it's a duplicate of #40 . Please take a look there and feel free to delete/close this issue

**Comment by arnaudgiuliani** [comment]
yeah if it's the same, let's keep one ticket. Please reopen if differs 👍
