### ISSUE TITLE
Disable binding for definition annotations generated code

### ISSUE THREAD

**Issue by andriishpek-sigma** [InsertKoinIO/koin-annotations#45]
**Is your feature request related to a problem? Please describe.**
Currently definition annotations (@Factory etc.) generate `binds` code for all annotated classes that implement interface

**Describe the solution you'd like**
A possibility to disable `binds` code block

**Comment by arnaudgiuliani** [comment]
you can specify `binds` in the annotation parameter if you want 🤔
