### ISSUE TITLE
Adding a new annotation for cross injection

### ISSUE THREAD

**Issue by aids61517** [InsertKoinIO/koin-annotations#47]
I have classes:

````
class ComposeHandler(private val postId: String)
````
````
class ComposeViewModel(private val composeHandler: ComposeHandler): ViewModel
````

Before using Koin Annotation, I registered Koin module like this:

````
    factory { params -> 
        ComposeHandler(params.get()) 
    }

    viewModel { parameters ->
        ComposeViewModel(
            composeHandler = get<ComposeHandler> { parameters },
        )
    }
````
I tried to adding annotation for both classes
````
@Factory
class ComposeHandler(
    @InjectedParam private val postId: String
)
````
````
@KoinViewModel
class ComposeViewModel(private val composeHandler: ComposeHandler): ViewModel
````
And gen code would be like this:
````
factory(qualifier=null) { params -> my.package.ComposeHandler(params.get()) }
viewModel(qualifier=null) { my.packgage.ComposeViewModel(get()) }
````

According to gen code by Koin Annotation, I can't pass parameters to `ComposeHandler`.
So I can't use annotation in this case
I think adding a new annotation can solve this problem
````
@KoinViewModel
class ComposeViewModel(
   @NewAnnotation private val composeHandler: ComposeHandler
): ViewModel
````
and gen code is
````
viewModel(qualifier=null) { params -> my.packgage.ComposeViewModel(get { parametersOf(params) }) }
````

Koin project used and used version (please complete the following information):
koin-core version 3.2.0
koin-annotation 1.0.1
ksp version 1.6.10-1.0.4

**Comment by arnaudgiuliani** [comment]
> According to gen code by Koin Annotation, I can't pass parameters to ComposeHandler.

Yes for now it's a limitation. It's not cascading parameters

**Comment by arnaudgiuliani** [comment]
will be invovled in Koin core development 👍
