### ISSUE TITLE
Keep up to date with Kotlin/Ksp versions

### ISSUE THREAD

**Issue by BugsBunnyBR** [InsertKoinIO/koin-annotations#48]
**Is your feature request related to a problem? Please describe.**
As far as I know, we need to match all ksp plugins with a given Kotlin version and there were new releases of kotlin and ksp in the last few months that would make the usage of this project a bit risky or incompatible.

**Describe the solution you'd like**
Would it be possible to keep this project updated with the current releases of Kotlin and Ksp? At least with the stable releases?

**Comment by arnaudgiuliani** [comment]
sure, updates are coming
