### ISSUE TITLE
Required Android ApplicationContext and ActivityContext Injection support 

### ISSUE THREAD

**Issue by jegalirisoft** [InsertKoinIO/koin-annotations#49]
I'm looking injecting the context as parameter inside the module method definitions. could you please add a support like Hilt annotations   ?

1. ApplicaitonContext
2. ActivityContext.    

```

@Module
class DatabaseModule {
    @Single
    fun provideBoxStore(context: Context): BoxStore {
        var boxStore = MyObjectBox.builder().androidContext(context).build()
        if (BuildConfig.DEBUG) {
            val started: Boolean = Admin(boxStore).start(context)
        }
        return boxStore
}
```

**Comment by mtrakal** [comment]
same for single class annotation:

```kotlin

interface RemoteService {}

@Single
class ReviewRepository(
    private val remoteService: RemoteService,
    private val context: Context
) {
 ....
}
```

**Comment by arnaudgiuliani** [comment]
Injecting a module function parameter like `context: Context` can be done directly without any annotation. You just need to setup your Android context at `startKoin`

> single { ReviewRepository(get(), androidContext()) }
equivalent is also `single { ReviewRepository(get(), get()) }`
