### ISSUE TITLE
Unresolved reference: StringQualifier

### ISSUE THREAD

**Issue by jsamse** [InsertKoinIO/koin-annotations#5]
**Describe the bug**
`Unresolved reference: StringQualifier` when using `@Named` for constructor parameter in class marked with `@Single`.

**To Reproduce**
1. Setup a KMP project
2. Mark a class with `@Single`
3. Mark a constructor parameter with `@Named`
4. Build
5. See error

**Expected behavior**
Successful build

**Koin project used and used version (please complete the following information):**
`koin-core version 3.2.0-beta-1`
`koin-ksp 1.0.0-beta-1`
`ksp version 1.6.10-1.0.4`

**Comment by arnaudgiuliani** [comment]
> Unresolved reference: StringQualifier 

this is in generated module I guess

**Comment by hennihaus** [comment]
I have the same bug. There is missing the import path for StringQualifier in the generated module.

**Comment by arnaudgiuliani** [comment]
Thanks, should be quick to fix

**Comment by arnaudgiuliani** [comment]
fixed in next beta 1.0.0-beta-2 - [d6725c4](https://github.com/InsertKoinIO/koin-annotations/commit/d6725c41e3df25278f0604a55dc0f9e9edf6f143)

**Comment by iota9star** [comment]
@arnaudgiuliani `1.0.0-beta-2` was not successfully publish to maven repository.

**Comment by arnaudgiuliani** [comment]
it's online
