### ISSUE TITLE
Native compilation not working since 1.0.1

### ISSUE THREAD

**Issue by gbourassa** [InsertKoinIO/koin-annotations#51]
**Describe the bug**
I have kotlin multi-platform project, in which in only have koin-related annotations in my common module. I'm using the `kspCommonMainMetadata` approach to generate module code.

Since version 1.0.1 of koin-annotations, attempting to compile with a native target (for instance `iosArm64`), I get a compilation error on the generated code:

```
[someModuleName].kt: (1, 7): Unresolved reference: JvmName
[someModuleName].kt: (2, 7): Unresolved reference: JvmMultifileClass
```

Since this commit (https://github.com/InsertKoinIO/koin-annotations/commit/72c3d6f50eab672487521a7ab4c413e460389dbb), there is now this header at the top of the module file:

```
@file:JvmName("${genName}Gen")
@file:JvmMultifileClass
```

But these annotations are not imported. When using java-based targets (ie. Android), this seems to work ok. But not on native targets.

**Expected behavior**
`JvmName` and `JvmMultifileClass` should probably be imported in the generated code.

**Koin project used and used version (please complete the following information):**
`koin-core version 3.2.0`
`koin-annotations version 1.0.1`

**Comment by arnaudgiuliani** [comment]
Yeah, problem is it's causing issue in KMM side :/ 

see https://github.com/InsertKoinIO/koin-annotations/issues/41
