### ISSUE TITLE
injection of android navigationGraph args

### ISSUE THREAD

**Issue by mtrakal** [InsertKoinIO/koin-annotations#53]
**Is your feature request related to a problem? Please describe.**
I would like to use koin-annotations to inject ViewModel with [android navigationGraph parameters](https://developer.android.com/guide/navigation/navigation-pass-data).

Currently I inject it without annotations: 
```kotlin
viewModel { (args: MainFragmentArgs) -> MainViewModel(MainViewState(args), get()) }
```

**main_navigation_graph.xml**
```xml
<fragment
        android:id="@+id/fragment_main"
        android:name="my.app.MainFragment"
        tools:layout="@layout/fragment_main">

        <argument
            android:name="data"
            app:argType="string" />

    </fragment>
```
```kotlin
class MainFragment : ... {
    override val viewModel: MainViewModel by viewModel {
        parametersOf(MainFragmentArgs.fromBundle(requireArguments()))
    }
}

interface ViewState

class MainViewState(args: MainFragmentArgs) : ViewState {
    val data = args.data
}

abstract class BaseViewModel<VS : ViewState> : ViewModel(), CoroutineScopeOwner, DefaultLifecycleObserver, KoinComponent {}

class MainViewModel(
    override val viewState: MainViewState,
    private val repository: MainRepository
) : BaseViewModel<MainViewState>() {
...
}
```

**Describe the solution you'd like**
With annotation processor I would like to inject Navigation graph args, but I think, that's not possible now, because classes are not annotated by Koin.

```kotlin
@Factory
class MainViewState(...

@KoinViewModel
class MainViewModel(...
```

So when I use it with this annotations I get: 
```
org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'my.app.MainViewModel',binds:my.app.BaseeViewModel]
Caused by: org.koin.core.error.NoBeanDefFoundException: |- No definition found for class:'my.app.MainViewState'. Check your definitions!
```
because it can't inject `val args: MainFragmentArgs` I think, because it's added to viewModel manually now by `viewModel { (args: MainFragmentArgs) -> `

I tried to use: 
```kotlin
@Factory(binds = [MainFragmentArgs::class])
class MainViewState(
```
and
```kotlin
class MainViewState(
    @InjectedParam val args: MainFragmentArgs,
```
but it's not annotated by Koin, so I think, that's still not possible use it in this way.

**Comment by mtrakal** [comment]
when using same code, but without argument from navigation graph, all works as expected with:
```kotlin
class MainFragment :...
    override val viewModel: MainViewModel by viewModel()
}

@Factory
class MainViewState(...

@KoinViewModel
class MainViewModel(...
```

**Comment by mtrakal** [comment]
io-insert-koin = "3.2.0"
io-insert-koin-ksp = "1.0.1"

Used packages:
io.insert-koin:koin-android
io.insert-koin:koin-annotations
io.insert-koin:koin-androidx-navigation
io.insert-koin:koin-androidx-workmanager
io.insert-koin:koin-ksp-compiler

**Comment by arnaudgiuliani** [comment]
You can get the injected parameters. But you can't directly transform it with `MainViewState(args)`

Did you tried a backup field in your MainViewModel, to transform it from there?

I would try with something : 

```kotlin
class MainViewModel(args: MainFragmentArgs){

    val state = MainViewState(args)
}

```
