### ISSUE TITLE
module type bug

### ISSUE THREAD

**Issue by vjh0107** [InsertKoinIO/koin-annotations#58]
**Describe the bug**
type must be specified when a module field is in a module

**To Reproduce**
1. not specify a module type in the module field in a module

**Expected behavior**
module class must be generated

**Koin project used and used version (please complete the following information):**
core version 3.2.0
annotations version 1.0.1

video:
https://imgur.com/USbXqjq

**Comment by arnaudgiuliani** [comment]
You must keep using class modules between them, and avoid mix Module DSL & Class Module annotations
