### ISSUE TITLE
Koin annotations has a dependency on junit

### ISSUE THREAD

**Issue by dustinconrad** [InsertKoinIO/koin-annotations#6]
**Describe the bug**
Unnecessary dependency on junit in `io.insert-koin:koin-annotations:1.0.0-beta-1`

**To Reproduce**
This is causing a conflict in my local project, but you can see it defined in the [gradle file](https://github.com/InsertKoinIO/koin-annotations/blob/e624614aa1b51b6e5ae6b28258223d560397b199/compiler/koin-annotations/build.gradle#L51)

**Expected behavior**
Non-test libraries should not take a dependency on junit

**Koin project used and used version (please complete the following information):**
`io.insert-koin:koin-annotations:1.0.0-beta-1`

**Comment by arnaudgiuliani** [comment]
good catch
