### ISSUE TITLE
Lazy dependency in module

### ISSUE THREAD

**Issue by esial** [InsertKoinIO/koin-annotations#61]
Using DSL I could create dependency in a module like this:
single { MyDependency(get(), inject()) }
Inject returns `kotlin.Lazy` so there was a possibility to avoid circular dependencies for example when I have a network interceptor which can perform a network request.

Using annotations, generated class uses only get() to obtain dependency. Is there any way to force change this to inject()?

**Comment by alperenbabagil** [comment]
Feel free to give a like to this pr :) https://github.com/InsertKoinIO/koin-annotations/pull/59

**Comment by arnaudgiuliani** [comment]
I would avoid having such type, but propose to detect `Lazy` type directly to generate the right DSL. I believe there is no need of special annotation here

**Comment by arnaudgiuliani** [comment]
since Koin Annotations 1.2 we are detecting `Lazy` type to generate `ìnject` instead of `get` 👍
