### ISSUE TITLE
A class that extends an interface on a different Gradle module won't generate proper binds

### ISSUE THREAD

**Issue by antoniolg** [InsertKoinIO/koin-annotations#7]
**Describe the bug**
If you use a `@Factory` or `@Single` annotation on a class that extends an interface in another Gradle module, the generated code won't include the proper `bind` to the interface. Even manually adding the class to the `binds` annotation will fail.

**To Reproduce**
1. Create a project with two modules (I tried with an Android app and a kotlin library)
2. Create an interface in the second module
3. Create a class implementing that interface in the first module
4. Annotate the class with `@Single` or `@Factory`

You can try it in [this repository](https://github.com/DevExperto/architect-coders-v2/tree/koin-annotations), for example [with this class](https://github.com/DevExperto/architect-coders-v2/blob/koin-annotations/app/src/main/java/com/devexperto/architectcoders/data/PlayServicesLocationDataSource.kt). You will need a TheMovieDb api key though.

**Expected behavior**
Binds should be properly generated, both automatically and manually.

**Koin project used and used version (please complete the following information):**
koin-annotations 1.0.0-beta-1

**Comment by Kamil-H** [comment]
I'm also facing this issue for the type that is declared in 3rd party library.

**Comment by arnaudgiuliani** [comment]
Thanks for reporting. Let me see

**Comment by arnaudgiuliani** [comment]
seems that we would just need to be sure to have the complete package generated.
