### ISSUE TITLE
WorkManager documentation for using Annotations

### ISSUE THREAD

**Issue by tyczj** [InsertKoinIO/koin-annotations#71]
All the documentation for using androids work manager is for when using DSL, nothing shows how to setup work manager to be able to use with Annotations

**Comment by arnaudgiuliani** [comment]
Yes, I need to implement the needed annotation 👍

**Comment by arnaudgiuliani** [comment]
@KoinWorker annotation has been added. It will be available in Koin Annotations 1.2.0
