### ISSUE TITLE
Support generating definitions for object declarations

### ISSUE THREAD

**Issue by ithersta** [InsertKoinIO/koin-annotations#72]
**Is your feature request related to a problem? Please describe.**
I use JetBrains Exposed and I have several tables declared like so:
```kotlin
object Users : LongIdTable() {
    val name: Column<String> = varchar("name", length = 256)
    ...
}
```
I want to annotate all tables with `@Single` and then use `getAll<Table>()`:
```kotlin
SchemaUtils.createMissingTablesAndColumns(*getAll<Table>().toTypedArray())
```

But the generated definitions for objects call a non-existent constructor and the project doesn't compile.
```kotlin
single(qualifier=null) { auth.data.tables.Users() }
```

**Describe the solution you'd like**
Generate a proper definition for object declaration without calling a constructor.

**Describe alternatives you've considered**
I tried turning object into a class but it's not ideal since the object is used a lot in queries like so:
```kotlin
Users.batchInsert(user.areas) {
    this[Users.name] = user.name
    ...
}
```

**Target Koin project**
koin-annotations

**Comment by ninja-** [comment]
`object` compiles to an internal class without public constructor and one JVM-global `INSTANCE` field with the instance.
It really doesn't sound like a good match for a DI system like Koin.

I don't know exposed that well, but you probably should turn the object back into class, and only reference it using injected instance, even if it may queries a bit more annoying.

Alternatively, try binding a factory where `Users` is the type and returned data is `Users` itself - the object.

**Comment by arnaudgiuliani** [comment]
yep, not sure to see the real case. Also Ktor is generating content, not sure about compatibility with Koin Annotations here 🤔

**Comment by ithersta** [comment]
Well, my use case is to automatically find all the tables in my code (and canonically they are objects in Exposed) so I don't have to list them manually during schema creation. It's not really about dependency injection, more like plugin discovery, so maybe it's out of scope for Koin.

**Comment by ithersta** [comment]
I can submit a PR if you want to

**Comment by undermark5** [comment]
A work around is to declare `operator fun invoke() = this` on the objects. It may not be pretty, but it is a valid work around (koin really should only call the constructor if the definition isn't an object (which is known during KSP), I ran into the same issue with defining a module as an object and the invoke operator function did the trick)

**Comment by undermark5** [comment]
This seems like something similar to #107 would work here.

**Comment by arnaudgiuliani** [comment]
yes duplicated

**Comment by undermark5** [comment]
Not exactly. Last I checked #107 only impacted module definitions, not dependency definitions. That is that I don't think that #107 in it's current form provides a solution for this issue.
