### ISSUE TITLE
koin annotations cause compiler warning

### ISSUE THREAD

**Issue by eekboom** [InsertKoinIO/koin-annotations#79]
I like to have my build configured to fail on warnings (`-Werror` or `compilerOptions { allWarningsAsErrors = true }` in gradle).

Unfortunately, using koin annotations causes compiler warnings and it is tricky in gradle to set the compiler up to ignore warnings only in the generated code.

Here is the warning:

```
> Task :app:compileKotlin
w: file://~/dev/github/acme/foobar/app/build/generated/ksp/main/kotlin/org/koin/ksp/generated/KoinAppModuleGende$acme$foobar.kt:7:6 Variable 'moduleInstance' is never used
```

The source of the generated module file looks like this
```
public val de_acme_foobar_KoinAppModule = module {
	val moduleInstance = de.acme.foobar.KoinAppModule()
	single(qualifier=null) { de.acme.foobar.user.UserService(get()) } 
	...
```
and moduleInstance is indeed unused.

Could you make the code so that it does not cause any compiler warnings?
Even just adding `@Suppress("UNUSED_VARIABLE") ` would be fine.

koin 3.4.0
koin-annotations 1.2.0

**Comment by arnaudgiuliani** [comment]
yep, it would be better to have clean code 👍

**Comment by lockhartja** [comment]
@eekboom what was your workaround? Disable the ErrorAsWarning flag? @arnaudgiuliani is insight on why this particular line is being written...I didn't have the error a few weeks ago...but after a small rewrite the error appeared.

**Comment by rjspies** [comment]
Hi, are there news on this matter by any chance?

I found that not using `ComponentScan` but writing the providers as members of the `Module` could be a more or less valid workaround for the time being:
```kotlin
@Module
class AppModule {
    @Single
    fun provideDatabase(context: Context): WeightDatabase {
        return WeightDatabase.getDatabase(context)
    }

    @Single
    fun provideWeightDao(database: WeightDatabase): WeightDao {
        return database.weightDao()
    }

    @Single
    fun provideWeightService(dao: WeightDao): WeightService {
        return WeightService(dao)
    }
}
```

**Comment by arnaudgiuliani** [comment]
this is a warning, no? 🤔 not an error

**Comment by eekboom** [comment]
@arnaudgiuliani Yes, "only" a warning, but it prevents me from enforcing clean style in **our own** code.
I'd like to configure gradle to treat warnings as errors (so people clean up our code instead of letting it generate warnings) ... but I can't because koin-generated code already creates warnings.

**Comment by arnaudgiuliani** [comment]
sure, something need to be cleaned 👍

**Comment by arnaudgiuliani** [comment]
fixed in PR
