### ISSUE TITLE
Generate empty module on multiplatform for common code

### ISSUE THREAD

**Issue by tristancaron** [InsertKoinIO/koin-annotations#8]
**Describe the bug**

When a module class is created in common code, but does not have any dependencies, the code fails to compile because `.module` does not exist.

**To Reproduce**

In common code
```kotlin
package com.my.package

import org.koin.core.annotation.ComponentScan
import org.koin.core.annotation.Module

@Module
@ComponentScan("com.my.package")
class MyPackageModule
```

In platform specific code
```kotlin
package com.my.package.usecase

import org.koin.core.annotation.Single

@Single
class GetUserUseCaseImpl : GetUserUseCase {
    override fun invoke() = "user"
}
```

Back in common
```kotlin
// Use Koin Generation
import org.koin.ksp.generated.*

// ...

startKoin {
    modules(MyPackageModule().module)
}
```

Then run code generation via `./gradlew kspCommonMainKotlinMetadata`

The file `default.kt` is generated but empty (that's fine). The file `MyPackageModuleGen.kt` is missing, so common code is not aware of the extension `.module`.

When running the code directly on the targeted platform, the files needed for the platform are all generated correctly (`MyPackageModuleGen.kt` is created in the correct directory).

It does not prevent the code from compiling, but it stays red in common code.

**Expected behavior**

Generate usable code for common. Maybe use `expect` keyword?

**Koin project used and used version (please complete the following information):**
```
val koinVersion= "3.2.0-beta-1"
val koinKspVersion= "1.0.0-beta-1"
id("com.google.devtools.ksp") version "1.6.20-RC-1.0.4"
```

**Additional moduleDefinition**
Add any other moduleDefinition about the problem here.

**Comment by arnaudgiuliani** [comment]
Need to check with KSP multiplatform generation part 👍

**Comment by arnaudgiuliani** [comment]
did you check https://github.com/InsertKoinIO/koin-annotations/issues/20 ?

**Comment by arnaudgiuliani** [comment]
KMP need special dependency setup

**Comment by tristancaron** [comment]
Thanks. We will take a look with the team and see if it resolves also issues with clashing generated code. (Like compiling for Android and code namespace issues)

**Comment by tristancaron** [comment]
Here how I define my KSP dependency (can be improved 🤫)
```kt
dependencies {
    add("kspCommonMainMetadata", "io.insert-koin:koin-ksp-compiler:$koinKspVersion")
    add("kspAndroid", "io.insert-koin:koin-ksp-compiler:$koinKspVersion")
    add("kspAndroidTest", "io.insert-koin:koin-ksp-compiler:$koinKspVersion")
    add("kspIosArm64", "io.insert-koin:koin-ksp-compiler:$koinKspVersion")
    add("kspIosArm64Test", "io.insert-koin:koin-ksp-compiler:$koinKspVersion")
    add("kspIosX64", "io.insert-koin:koin-ksp-compiler:$koinKspVersion")
    add("kspIosX64Test", "io.insert-koin:koin-ksp-compiler:$koinKspVersion")
    add("kspNative", "io.insert-koin:koin-ksp-compiler:$koinKspVersion")
}
```

Compiling for my targets work, even if the highlight is not working in the IDE
![image](https://user-images.githubusercontent.com/9624669/167051783-162ce8f5-be69-4f2c-9408-09a613b5161a.png)

We can get the highlight by running the script `./gradlew :shared:kspCommonMainKotlinMetadata` and adding the following
```kt
val commonMain by getting {
  kotlin.srcDirs("build/generated/ksp/metadata/commonMain/kotlin")
}
```

But, if the module is empty in common code, it is it not generated.
![image](https://user-images.githubusercontent.com/9624669/167051980-054e0b6c-2e52-46a9-8fae-32f8389df6da.png)

This is the module definition
```kt
package com.me.deviceInfo.di

import org.koin.core.annotation.ComponentScan
import org.koin.core.annotation.Module
import org.koin.core.annotation.Single

@Module
@ComponentScan("com.me.deviceInfo")
class DeviceInfoModule
```

And how it looks like in the common code
![image](https://user-images.githubusercontent.com/9624669/167052177-24baa97b-5b73-41a4-a868-3624cab6ae87.png)

There is only interfaces that must get an implementation from the platforms.

So, in order to force Koin generating something, we did
```kt
package com.me.deviceInfo.di

import org.koin.core.annotation.ComponentScan
import org.koin.core.annotation.Module
import org.koin.core.annotation.Single

class Force

@Module
@ComponentScan("com.me.deviceInfo")
class DeviceInfoModule {
    @Single
    fun force() = Force()
}
```

Then we get full highlight.
![image](https://user-images.githubusercontent.com/9624669/167052416-d83c252b-0c97-4381-bd39-6dd9967e2fd5.png)

But at this stage, the code does not compile anymore, because it's trying to include the path we added earlier.
```bash
e: /Users/me/AndroidStudioProjects/KotlinProject/shared/build/generated/ksp/android/androidDebug/kotlin/org/koin/ksp/generated/AuctionModuleGen.kt: (4, 5): Conflicting declarations: public val AuctionModuleModule: Module, public val AuctionModuleModule: Module
```

I am probably missing something with KSP?

**Comment by arnaudgiuliani** [comment]
Give a try with `1.0.2` and check your path config against Simple project: https://github.com/InsertKoinIO/hello-kmp/tree/annotations

Try to reactivate each path, one by one
