### ISSUE TITLE
Annotations should allow to not automatically bind the component's parent interface

### ISSUE THREAD

**Issue by bogdanzurac** [InsertKoinIO/koin-annotations#82]
**Is your feature request related to a problem? Please describe.**
The following setup is given:

```
interface Animal

@Single
class Dog : Animal

@Single
class Cat : Animal

@Module
@ComponentScan
class AnimalModule {

    @Single
    fun animal(cat: Cat, dog: Dog): Animal = if (randomBoolean()) cat else dog
}
```
We'd like to choose dynamically at runtime which implementation of the `Animal` interface we want to inject. However, the default behaviour of the `Single` annotation will automatically bind each of the 2 `Animal` implementations to the `Animal` class, which is wrong and adds unpredictability towards which of the 2 classes will be actually injected at runtime.

**Describe the solution you'd like**
There should be a way to turn off this behaviour and thus allow both 1) the injection of the individual implementations, such that they can still be injected in the `AnimalModule` as well as 2) the ability to bind ourselves manually which implementation we want to the `Animal` interface.

**Comment by arnaudgiuliani** [comment]
I can propose to fix this, by allowing to override default binding like follow:

```kotlin
@Single(binds = [])
class Dog : Animal

@Single(binds = [])
class Cat : Animal

@Module
@ComponentScan
class AnimalModule {

    @Factory
    fun animal(cat: Cat, dog: Dog): Animal = if (randomBoolean()) cat else dog
}
```

with `binds = []` we force to empty any extra binding. Your case then work with `get<Animal>()`

**Comment by bogdanzurac** [comment]
That would solve the issue, indeed.

However, I'd argue that the API surface would look a bit weird. Would it be possible to automatically disable interface binding without manually specifying that with a empty array in case Koin detects multiple subclasses?

**Comment by arnaudgiuliani** [comment]
by design, we are scanning bound types automatically. It can be an option, to activate or not later.

**Comment by arnaudgiuliani** [comment]
I close the ticket for now 👍 The "explicit binding" mode can be discuss elsewhere

**Comment by bogdanzurac** [comment]
I'm confused. The current implementation of `Single(binds: Array)` automatically binds the calling component to its parent interface. Overriding the `binds` parameter doesn't change that. So this needs to be changed in order to support the code snippet from the initial comment. Why close down the issue then?

**Comment by bogdanzurac** [comment]
@arnaudgiuliani could you please elaborate more on the above?

**Comment by arnaudgiuliani** [comment]
Did you check last 1.2.2, I believe casting is better

**Comment by bogdanzurac** [comment]
Yep, I can confirm that with 1.2.2 the setup mentioned in https://github.com/InsertKoinIO/koin-annotations/issues/82#issuecomment-1568515279 works nicely. Thanks!
