### ISSUE TITLE
Definitions with createdAtStart=true and no qualifier aren't generated correctly

### ISSUE THREAD

**Issue by ithersta** [InsertKoinIO/koin-annotations#84]
**Describe the bug**
`@Single(createdAtStart = true)` with no qualifier generates invalid code

**To Reproduce**
1. Annotate class with `@Single(createdAtStart = true)`
2. Do not specify qualifier
3. The generated code contains an extra comma and is invalid:
```kotlin
single(,createdAtStart=true) { … }
```

**Expected behavior**
The generated code is valid

**Koin project used and used version (please complete the following information):**
`koin-annotations version 1.2.1`

**Comment by arnaudgiuliani** [comment]
duplicated from https://github.com/InsertKoinIO/koin/issues/1604
