### ISSUE TITLE
JS support

### ISSUE THREAD

**Issue by NorbertSandor** [InsertKoinIO/koin-annotations#89]
I tried to use koin with _js_ target but it does not work, there exists no _js_ build of the library.
In the source code I found the related targets commented out with the remark:

> Array in Annotations not yet supported :\

May I ask what it means and when can we expect _js_ support?

**Comment by arnaudgiuliani** [comment]
Js target is not yet active, because kotlin annotations array properties are not yet compatible with js.
Need to check with Kotlin team.

**Comment by NorbertSandor** [comment]
Thanks for the info, maybe is there a KT issue we can follow or vote for?

**Comment by arnaudgiuliani** [comment]
if find it, please post it. else I need to dig into it 👍

**Comment by NorbertSandor** [comment]
I haven't found any related (open) issue, but maybe I have just overlooked...

**Comment by arnaudgiuliani** [comment]
fixed in 1.3.0

**Comment by NorbertSandor** [comment]
(Can we expect the 1.3.0 release anytime soon? :) )

**Comment by arnaudgiuliani** [comment]
this week or next week 👍
