### ISSUE TITLE
Annotation class was declared in module.

### ISSUE THREAD

**Issue by aerain** [InsertKoinIO/koin-annotations#9]
Sorry for english. 😅 

**Describe the bug**
When I created annotation and annotate as Single class, It was declared in defaultModule unintentionally.
Also, When I created class that want to declare module, and annotate my class, It won't be declared in defaultModule

**To Reproduce**

1. created annotation class
```kt
@Single(createdAtStart = true)
annotation class RestApi
```
2. annotate my class
```kt
@RestApi
class HelloController {
    ....
}
```
3. build
4. defaultModule result
```kt
val defaultModule = module {
    single(qualifier=null, createdAtStart=true) { some.package.RestApi() } // only annotation class was declared.
}
```

**Expected behavior**
What I Expected.
```kt
val defaultModule = module {
    single(qualifier=null, createdAtStart=true) { some.package.HelloController() }
}
```

**Koin project used and used version (please complete the following information):**
koin-core version 3.2.0-beta-1
koin-annotation 1.0.0-beta-1
ksp-version 1.6.10-1.0.2

**Additional moduleDefinition**
Nothing.

**Comment by arnaudgiuliani** [comment]
Not sure how KSP allow to scoot annotations behind your own annotation 🤔 
have to check
