### ISSUE TITLE
Generated modules are global

### ISSUE THREAD

**Issue by lukelast** [InsertKoinIO/koin-annotations#92]
**Is your feature request related to a problem? Please describe.**
I'm trying to create many instances of `KoinApplication` to use in tests that run in parallel. Currently this not possible because the generated module instances are set in global variables.

For example, code like this:
```Kotlin
@Module
@ComponentScan("blah")
class ScanModule
```

Will generate code like this:

```kotlin
public val foo_ScanModule : Module = module {
    single() { Blah() }
}
public val ScanModule.module : org.koin.core.module.Module get() = foo_ScanModule
```

The `foo_ScanModule` keeps a single global instance of the module, which causes singletons to be shared among all koin instances created with this module.

**Describe the solution you'd like**
I think calling `ScanModule.module` should create a new instance of the module each time.

**Comment by undermark5** [comment]
Is it ever necessary to reference the module outside of instantiating Koin/multiple times? If so, couldn't this proposal cause problems? I'm not certain that referencing a module multiple times is ever needed, so this may not actually cause any problems.

**Comment by lukelast** [comment]
I see 2 options for implementing a fix.

1. Change the existing `ScanModule.module` to return a new instance of the module each time.
2. Keep the current behavior, but allow access to get new instances of the module. Like `ScanModule.createModule()`

Either would work for me. With option 1 you can still create and use a global module that would be shared across multiple koin instances, you would just have to do it explicitly.

**Comment by arnaudgiuliani** [comment]
Ok interesting 🤔 need to check the global impact of this

**Comment by lukelast** [comment]
You're breaking my heart stale bot.

**Comment by arnaudgiuliani** [comment]
duplicated with #102
